name: sample

on:
  workflow_dispatch:
    inputs:
      tag:
        description: '`vx.y.z-릴리즈` 형태로 버전을 입력해주세요. `vx.y.z`도 가능합니다.'
        required: true
        default: v1.2.3-rc1

jobs:
  pull:
    runs-on: ubuntu-latest
    steps:
      - name: git pull
        uses: convictional/trigger-workflow-and-wait@v1.3.0
        with:
          owner: spaceone-dev
          repo: actions
          github_token: ${{ secrets.PAT_TOKEN }}
          workflow_file_name: deploy.yml
          ref: master
          wait_interval: 10
          inputs: '{"group" : "backend", "repository" : "${{ github.repository }}"}'
          trigger_workflow: true
          wait_workflow: true

  CI:
    runs-on: ubuntu-latest
    needs: pull
    steps:
      - uses: actions/checkout@v2
      - name: git pull
        run: git pull origin master
      - run: echo "CI&CD"