name: "[dispatch] release all core services"
on:
  workflow_dispatch:
    inputs:
      ref_branch:
        description: 'branch referenced by each repositories (only master and release-x.y.z are allowed)'
        required: true
        default: 'master'
      version:
        description: 'enter version(x.y.z)'
        required: true
        default: '1.0.0'
      container_arch:
        type: choice
        description: 'choose container architecture'
        default: linux/amd64
        options:
        - "linux/amd64"
        - "linux/amd64,linux/arm64"

env:
  ARCH: ${{ github.event.inputs.container_arch }}
  BRANCH: ${{ github.event.inputs.ref_branch }}
  VERSION: ${{ github.event.inputs.version }}
  SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}

jobs:
  core_console:
    if: github.repository_owner == 'cloudforet-io'
    runs-on: ubuntu-latest
    steps:
      - name: task
        uses: benc-uk/workflow-dispatch@v1
        with:
          token: ${{ secrets.PAT_TOKEN }}
          repo: cloudforet-io/console
          workflow: dispatch_release.yaml
          ref: ${{ env.BRANCH }}
          inputs: '{"version": "${{ env.VERSION }}", "container_arch": "${{ env.ARCH }}"}'

  core_console_api:
    needs: core_console
    runs-on: ubuntu-latest
    steps:
      - name: task
        uses: benc-uk/workflow-dispatch@v1
        with:
          token: ${{ secrets.PAT_TOKEN }}
          repo: cloudforet-io/console-api
          workflow: dispatch_release.yaml
          ref: ${{ env.BRANCH }}
          inputs: '{"version": "${{ env.VERSION }}", "container_arch": "${{ env.ARCH }}"}'

  core_python_service:
    strategy:
      fail-fast: false
      max-parallel: 4
      matrix:
        target: ['identity', 'secret', 'repository', 'plugin', 'config', 'inventory', 'monitoring', 'statistics', 'cost-analysis', 'notification', 'board', 'file-manager', 'dashboard', 'console-api-v2', 'supervisor']
    needs: core_console_api
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - name: task
        uses: benc-uk/workflow-dispatch@v1
        with:
          token: ${{ secrets.PAT_TOKEN }}
          repo: cloudforet-io/${{ matrix.target }}
          workflow: dispatch_release.yaml
          ref: ${{ env.BRANCH }}
          inputs: '{"version": "${{ env.VERSION }}", "container_arch": "${{ env.ARCH }}"}'

  tools:
    strategy:
      fail-fast: false
      matrix:
        target: ['spacectl']
    needs: core_python_service
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - name: task
        uses: benc-uk/workflow-dispatch@v1
        with:
          token: ${{ secrets.PAT_TOKEN }}
          repo: cloudforet-io/${{ matrix.target }}
          workflow: dispatch_release.yaml
          ref: ${{ env.BRANCH }}
          inputs: '{"version": "${{ env.VERSION }}", "container_arch": "${{ env.ARCH }}"}'

  doc:
    strategy:
      fail-fast: false
      matrix:
        target: ['docs', 'marketplace-assets']
    needs: tools
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - name: task
        uses: benc-uk/workflow-dispatch@v1
        with:
          token: ${{ secrets.PAT_TOKEN }}
          repo: cloudforet-io/${{ matrix.target }}
          workflow: dispatch_release.yaml
          ref: ${{ env.BRANCH }}
          inputs: '{"version": "${{ env.VERSION }}", "container_arch": "${{ env.ARCH }}"}'

  notify_to_slack:
    needs: [doc]
    runs-on: ubuntu-latest
    steps:
      - name: Slack
        if: always()
        uses: 8398a7/action-slack@v3.15.0
        with:
          status: ${{job.status}}
          fields: repo,message,commit,author,action,eventName,ref,workflow,job,took
          author_name: Github Action Slack
